import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "relative h-full font-sans antialiased ",
          inter.className
        )}
      >
        <main className="relative flex flex-col min-h-screen bg-dark-1">
          <Navbar />
          <div className="flex-1 flex-grow ">{children}</div>
        </main>
      </body>
    </html>
  );
}
