import type { Metadata } from "next";
import "./_styles/globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            "relative h-full font-sans antialiased overflow-hidden",
            inter.className
          )}
        >
          <main className="relative flex flex-col min-h-screen bg-dark-1 ">
            <Navbar />
            <div className="flex flex-grow">
              {/* Main Content */}
              <div className="flex-1 overflow-auto custom-scrollbar ">
                {children}
              </div>
            </div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
